stages:
  - triggers

run_go_ci:
  stage: triggers
  trigger:
    include:
      - local: .gitlab/workflows/go-workflow.yml
    strategy: mirror

run_ts_ci:
  stage: triggers
  trigger:
    include:
      - local: .gitlab/workflows/ts-workflow.yml
    strategy: mirror
